package Vista;

import Principal.VentanaPrincipal;
import javax.swing.JOptionPane;

/**
 *
 * @author NatxosS
 */
public class VentanaVerificacionCajero extends javax.swing.JPanel {

    /**
     * Creates new form VentanaVerificacionCajero
     */
    public VentanaPrincipal ventanaPrincipal;
    public Boolean cancelar = false;
    
    public String caja = "";
    public String cajero = "";
    
    public int txtSeleccionado = 1;
    
    public VentanaVerificacionCajero(VentanaPrincipal ventanaPrin) {
        
        this.ventanaPrincipal = ventanaPrin;
        initComponents();
    }
    
    public VentanaPrincipal getVentanaPrincipal() {
        
        return ventanaPrincipal;
    }
    
    //////////////////// ACCESO A VARIABLES //////////////////////////////////////
    
    public void setTxtCaja(String txtCaja) {
        
        this.txtCaja.setText(txtCaja);
    }
    
    public String getTxtCaja() {
        
        return txtCaja.getText();
    }
    
    public void setTxtCajero(String txtCajero) {
        
        this.txtCajero.setText(txtCajero);
    }
    
    public String getTxtCajero() {
        
        return txtCajero.getText();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        txtCaja = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtCajero = new javax.swing.JTextField();
        btnAceptar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel2.setText("CAJA: ");

        txtCaja.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtCaja.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCajaFocusGained(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel3.setText("Introduzca su código personal:");

        txtCajero.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        txtCajero.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtCajeroFocusGained(evt);
            }
        });

        btnAceptar.setFont(new java.awt.Font("Tahoma", 1, 16)); // NOI18N
        btnAceptar.setForeground(new java.awt.Color(0, 51, 204));
        btnAceptar.setText("ACEPTAR");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });

        jLabel1.setText("El código personal del empleado es el 15, esto tiene la función de que nadie");

        jLabel4.setText("ajeno a la empresa pueda registrar un pedido y a su vez quede registrado que");

        jLabel5.setText("empleado hizo el pedido.");

        jLabel6.setText("Esto es algo que no se me exigia pero que ");

        jLabel7.setText("he añadido yo para después crear una base de datos");

        jLabel8.setText("de empleados y una interfaz donde poder modificarlos.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtCajero, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(txtCaja, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8))
                                .addGap(102, 102, 102)
                                .addComponent(btnAceptar))
                            .addComponent(jLabel4)
                            .addComponent(jLabel1))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtCaja, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtCajero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnAceptar, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addContainerGap(22, Short.MAX_VALUE))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed

        caja = getTxtCaja();
        cajero = getTxtCajero();
        if (caja.equals("") || cajero.equals("")) {
            JOptionPane.showMessageDialog(null, "Falta algún dato");
            setTxtCaja("");
            setTxtCajero("");
        } else {
            ventanaPrincipal.verificarTrabajador(caja, cajero);
            setTxtCaja("");
            setTxtCajero("");
        }
    }//GEN-LAST:event_btnAceptarActionPerformed

    private void txtCajaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCajaFocusGained
        
        txtSeleccionado = 1;
    }//GEN-LAST:event_txtCajaFocusGained

    private void txtCajeroFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtCajeroFocusGained
        
        txtSeleccionado = 2;
    }//GEN-LAST:event_txtCajeroFocusGained


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAceptar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JTextField txtCaja;
    private javax.swing.JTextField txtCajero;
    // End of variables declaration//GEN-END:variables
}
