
package Principal.ventanasSubProductos;

/**
 *
 * @author NatxosS
 */
import Principal.VentanaPrincipal;
import Vista.*;
import Acciones.pedido.AccionesPedidoComidas;

public class SubComidas extends javax.swing.JPanel {

    /**
     * Creates new form SubComidas
     */
    public VentanaPrincipal ventanaPrincipal;
    public VentanaProductos ventanaProductos;
    public AccionesPedidoComidas accionesComidas;
    
    public int botonSeleccionado = 0;
    
    public String des1 = "cOMIDA";
    public String precio1 = "0.75";
    
    public String des2 = "Cola";
    public String precio2 = "3";
    
    public String des3 = "FcOMIDA";
    public String precio3 = "0.12";
    
    public String des4 = "FantaL";
    public String precio4 = "0.32";
    
    public String des5 = "cOMIDA";
    public String precio5 = "5.2";
    
    public String des6 = "cervez";
    public String precio6 = "7.1";
    
    public String des7 = "tintoo";
    public String precio7 = "3.98";
    
    public String des8 = "acucOMIDA1";
    public String precio8 = "12";
    
    public String des9 = "perrito";
    public String precio9 = "12";
    
    static Integer cantidad1 = 0;
    static Integer cantidad2 = 0;
    static Integer cantidad3 = 0;
    static Integer cantidad4 = 0;
    static Integer cantidad5 = 0;
    static Integer cantidad6 = 0;
    static Integer cantidad7 = 0;
    static Integer cantidad8 = 0;
    static Integer cantidad9 = 0;
    
    public SubComidas() {
        
        initComponents();
    }
    
    public SubComidas(VentanaPrincipal ventanaPrin, VentanaProductos ventanaProd) {
        
        this.setVentanaPrincipal(ventanaPrin);
        this.ventanaProductos = ventanaProd;
        this.accionesComidas = new AccionesPedidoComidas(this);
        initComponents();
    }

    public VentanaPrincipal getVentanaPrincipal() {
        
        return ventanaPrincipal;
    }
    
    public void setVentanaPrincipal(VentanaPrincipal ventanaPrincipal) {
        
        this.ventanaPrincipal = ventanaPrincipal;
    }
    
     //////////////////////////////////////// METODOS ///////////////////////////////////
    
    public void limpiarCantidades() {
        
        cantidad1 = 0;
        cantidad2 = 0;
        cantidad3 = 0;
        cantidad4 = 0;
        cantidad5 = 0;
        cantidad6 = 0;
        cantidad7 = 0;
        cantidad8 = 0;
        cantidad9 = 0;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelSubProductos = new javax.swing.JPanel();
        panelComidas1 = new javax.swing.JPanel();
        btnComida1 = new javax.swing.JButton();
        panelComidas2 = new javax.swing.JPanel();
        btnComida2 = new javax.swing.JButton();
        panelComidas3 = new javax.swing.JPanel();
        btnComida3 = new javax.swing.JButton();
        panelComidas4 = new javax.swing.JPanel();
        btnComida4 = new javax.swing.JButton();
        panelComidas5 = new javax.swing.JPanel();
        btnComida5 = new javax.swing.JButton();
        panelComidas6 = new javax.swing.JPanel();
        btnComida6 = new javax.swing.JButton();
        panelComidas7 = new javax.swing.JPanel();
        btnComida7 = new javax.swing.JButton();
        panelComidas8 = new javax.swing.JPanel();
        btnComida8 = new javax.swing.JButton();
        panelComidas9 = new javax.swing.JPanel();
        btnComida9 = new javax.swing.JButton();

        panelSubProductos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255), 2));
        panelSubProductos.setLayout(new java.awt.GridLayout(3, 5, 2, 2));

        panelComidas1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
        panelComidas1.setLayout(new java.awt.BorderLayout());

        btnComida1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnComida1.setForeground(new java.awt.Color(255, 0, 0));
        btnComida1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/subProductos/icon_kebab.jpg"))); // NOI18N
        btnComida1.setText("POLLO");
        btnComida1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComida1ActionPerformed(evt);
            }
        });
        panelComidas1.add(btnComida1, java.awt.BorderLayout.CENTER);

        panelSubProductos.add(panelComidas1);

        panelComidas2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
        panelComidas2.setLayout(new java.awt.BorderLayout());

        btnComida2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnComida2.setForeground(new java.awt.Color(255, 0, 0));
        btnComida2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/subProductos/icon_kebab.jpg"))); // NOI18N
        btnComida2.setText("TERNERA");
        btnComida2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComida2ActionPerformed(evt);
            }
        });
        panelComidas2.add(btnComida2, java.awt.BorderLayout.CENTER);

        panelSubProductos.add(panelComidas2);

        panelComidas3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
        panelComidas3.setLayout(new java.awt.BorderLayout());

        btnComida3.setForeground(new java.awt.Color(255, 0, 0));
        btnComida3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/subProductos/icon_patatasKebab.jpg"))); // NOI18N
        btnComida3.setText("Kebab, Patatas y Salsa");
        btnComida3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComida3ActionPerformed(evt);
            }
        });
        panelComidas3.add(btnComida3, java.awt.BorderLayout.CENTER);

        panelSubProductos.add(panelComidas3);

        panelComidas4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
        panelComidas4.setLayout(new java.awt.BorderLayout());

        btnComida4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnComida4.setForeground(new java.awt.Color(255, 0, 0));
        btnComida4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/subProductos/icon_hamburPollo.jpg"))); // NOI18N
        btnComida4.setText("POLLO");
        btnComida4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComida4ActionPerformed(evt);
            }
        });
        panelComidas4.add(btnComida4, java.awt.BorderLayout.CENTER);

        panelSubProductos.add(panelComidas4);

        panelComidas5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
        panelComidas5.setLayout(new java.awt.BorderLayout());

        btnComida5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnComida5.setForeground(new java.awt.Color(255, 0, 0));
        btnComida5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/subProductos/icon_hamburTerne.jpg"))); // NOI18N
        btnComida5.setText("TERNERA");
        btnComida5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComida5ActionPerformed(evt);
            }
        });
        panelComidas5.add(btnComida5, java.awt.BorderLayout.CENTER);

        panelSubProductos.add(panelComidas5);

        panelComidas6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
        panelComidas6.setLayout(new java.awt.BorderLayout());

        btnComida6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnComida6.setForeground(new java.awt.Color(255, 0, 0));
        btnComida6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/subProductos/icon_pizzaTurk.jpg"))); // NOI18N
        btnComida6.setText("Pizza turca");
        btnComida6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComida6ActionPerformed(evt);
            }
        });
        panelComidas6.add(btnComida6, java.awt.BorderLayout.CENTER);

        panelSubProductos.add(panelComidas6);

        panelComidas7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
        panelComidas7.setLayout(new java.awt.BorderLayout());

        btnComida7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnComida7.setForeground(new java.awt.Color(255, 0, 0));
        btnComida7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/subProductos/icon_ensaladacesar.jpg"))); // NOI18N
        btnComida7.setText("Ensalada Cesar");
        btnComida7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComida7ActionPerformed(evt);
            }
        });
        panelComidas7.add(btnComida7, java.awt.BorderLayout.CENTER);

        panelSubProductos.add(panelComidas7);

        panelComidas8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
        panelComidas8.setLayout(new java.awt.BorderLayout());

        btnComida8.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnComida8.setForeground(new java.awt.Color(255, 0, 0));
        btnComida8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/subProductos/icon_alitaCebolla.jpg"))); // NOI18N
        btnComida8.setText("Alitas y aros cebolla");
        btnComida8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComida8ActionPerformed(evt);
            }
        });
        panelComidas8.add(btnComida8, java.awt.BorderLayout.CENTER);

        panelSubProductos.add(panelComidas8);

        panelComidas9.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
        panelComidas9.setLayout(new java.awt.BorderLayout());

        btnComida9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnComida9.setForeground(new java.awt.Color(255, 0, 0));
        btnComida9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/subProductos/icon_perritoCal.jpg"))); // NOI18N
        btnComida9.setText("Perrito caliente");
        btnComida9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComida9ActionPerformed(evt);
            }
        });
        panelComidas9.add(btnComida9, java.awt.BorderLayout.CENTER);

        panelSubProductos.add(panelComidas9);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelSubProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 670, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(panelSubProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    ///////////////////////////////// EVENTOS SUBPRODUCTOS ///////////////////////////////////
    
    private void btnComida1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComida1ActionPerformed
        
        Integer cant = ventanaPrincipal.cant;
        if (cantidad1 != 0) {
            if (cant == 0) {                                                    
                cantidad1 = cantidad1 + 1;
            } else {
                cantidad1 = cantidad1 + cant;
                ventanaPrincipal.cant = 0;
            }
        } else {
            if (cant == 0) {                                                    
                cantidad1 = 1;
            } else {
                cantidad1 = cant;
                ventanaPrincipal.cant = 0;
            }
        }
        Integer codigo = 0001;
        Integer descuento = 10;
        Double precio = Double.parseDouble(precio1);
        Double subTotal = (precio * cantidad1) - (((precio * cantidad1)/100) * descuento);

        if (!btnComida1.getText().equals("Vacio")) {
            int estado = ventanaPrincipal.getVentanaActual();
            if (estado == 1) {
                ventanaProductos.setTxtDescripcion(des1);
                ventanaProductos.setTxtPrecio(precio1);
            } else {
                if (estado == 3) {
                    
                    accionesComidas.meterProducto(codigo, des1, precio, descuento, cantidad1);
                }
            }
        } else {
            ventanaProductos.getBtnCrear().setEnabled(true);
            ventanaPrincipal.mostrarPanelProductos();
        }
    }//GEN-LAST:event_btnComida1ActionPerformed

    private void btnComida2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComida2ActionPerformed
        
        Integer cant = ventanaPrincipal.cant;
        if (cantidad2 != 0) {
            if (cant == 0) {                                                    
                cantidad2 = cantidad2 + 1;
            } else {
                cantidad2 = cantidad2 + cant;
                ventanaPrincipal.cant = 0;
            }
        } else {
            if (cant == 0) {                                                    
                cantidad2 = 1;
            } else {
                cantidad2 = cant;
                ventanaPrincipal.cant = 0;
            }
        }
        Integer codigo = 0001;
        Integer descuento = 10;
        Double precio = Double.parseDouble(precio2);
        Double subTotal = (precio * cantidad2) - (((precio * cantidad2)/100) * descuento);

        if (!btnComida2.getText().equals("Vacio")) {
            int estado = ventanaPrincipal.getVentanaActual();
            if (estado == 1) {
                ventanaProductos.setTxtDescripcion(des2);
                ventanaProductos.setTxtPrecio(precio2);
            } else {
                if (estado == 3) {
                    
                    accionesComidas.meterProducto(codigo, des2, precio, descuento, cantidad2);
                }
            }
        } else {
            ventanaProductos.getBtnCrear().setEnabled(true);
            ventanaPrincipal.mostrarPanelProductos();
        }
    }//GEN-LAST:event_btnComida2ActionPerformed

    private void btnComida3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComida3ActionPerformed
        
        Integer cant = ventanaPrincipal.cant;
        if (cantidad3 != 0) {
            if (cant == 0) {                                                    
                cantidad3 = cantidad3 + 1;
            } else {
                cantidad3 = cantidad3 + cant;
                ventanaPrincipal.cant = 0;
            }
        } else {
            if (cant == 0) {                                                    
                cantidad3 = 1;
            } else {
                cantidad3 = cant;
                ventanaPrincipal.cant = 0;
            }
        }
        Integer codigo = 0001;
        Integer descuento = 10;
        Double precio = Double.parseDouble(precio3);
        Double subTotal = (precio * cantidad3) - (((precio * cantidad3)/100) * descuento);

        if (!btnComida3.getText().equals("Vacio")) {
            int estado = ventanaPrincipal.getVentanaActual();
            if (estado == 1) {
                ventanaProductos.setTxtDescripcion(des3);
                ventanaProductos.setTxtPrecio(precio3);
            } else {
                if (estado == 3) {
                    
                    accionesComidas.meterProducto(codigo, des3, precio, descuento, cantidad3);
                }
            }
        } else {
            ventanaProductos.getBtnCrear().setEnabled(true);
            ventanaPrincipal.mostrarPanelProductos();
        }
    }//GEN-LAST:event_btnComida3ActionPerformed

    private void btnComida4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComida4ActionPerformed
        
        Integer cant = ventanaPrincipal.cant;
        if (cantidad4 != 0) {
            if (cant == 0) {                                                    
                cantidad4 = cantidad4 + 1;
            } else {
                cantidad4 = cantidad4 + cant;
                ventanaPrincipal.cant = 0;
            }
        } else {
            if (cant == 0) {                                                    
                cantidad4 = 1;
            } else {
                cantidad4 = cant;
                ventanaPrincipal.cant = 0;
            }
        }
        Integer codigo = 0001;
        Integer descuento = 10;
        Double precio = Double.parseDouble(precio4);
        Double subTotal = (precio * cantidad4) - (((precio * cantidad4)/100) * descuento);

        if (!btnComida4.getText().equals("Vacio")) {
            int estado = ventanaPrincipal.getVentanaActual();
            if (estado == 1) {
                ventanaProductos.setTxtDescripcion(des4);
                ventanaProductos.setTxtPrecio(precio4);
            } else {
                if (estado == 3) {
                    
                    accionesComidas.meterProducto(codigo, des4, precio, descuento, cantidad4);
                }
            }
        } else {
            ventanaProductos.getBtnCrear().setEnabled(true);
            ventanaPrincipal.mostrarPanelProductos();
        }
    }//GEN-LAST:event_btnComida4ActionPerformed

    private void btnComida5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComida5ActionPerformed
        
        Integer cant = ventanaPrincipal.cant;
        if (cantidad5 != 0) {
            if (cant == 0) {                                                    
                cantidad5 = cantidad5 + 1;
            } else {
                cantidad5 = cantidad5 + cant;
                ventanaPrincipal.cant = 0;
            }
        } else {
            if (cant == 0) {                                                    
                cantidad5 = 1;
            } else {
                cantidad5 = cant;
                ventanaPrincipal.cant = 0;
            }
        }
        Integer codigo = 0001;
        Integer descuento = 10;
        Double precio = Double.parseDouble(precio5);
        Double subTotal = (precio * cantidad5) - (((precio * cantidad5)/100) * descuento);

        if (!btnComida5.getText().equals("Vacio")) {
            int estado = ventanaPrincipal.getVentanaActual();
            if (estado == 1) {
                ventanaProductos.setTxtDescripcion(des5);
                ventanaProductos.setTxtPrecio(precio5);
            } else {
                if (estado == 3) {
                    
                    accionesComidas.meterProducto(codigo, des5, precio, descuento, cantidad5);
                }
            }
        } else {
            ventanaProductos.getBtnCrear().setEnabled(true);
            ventanaPrincipal.mostrarPanelProductos();
        }
    }//GEN-LAST:event_btnComida5ActionPerformed

    private void btnComida6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComida6ActionPerformed
        
        Integer cant = ventanaPrincipal.cant;
        if (cantidad6 != 0) {
            if (cant == 0) {                                                    
                cantidad6 = cantidad6 + 1;
            } else {
                cantidad6 = cantidad6 + cant;
                ventanaPrincipal.cant = 0;
            }
        } else {
            if (cant == 0) {                                                    
                cantidad6 = 1;
            } else {
                cantidad6 = cant;
                ventanaPrincipal.cant = 0;
            }
        }
        Integer codigo = 0001;
        Integer descuento = 10;
        Double precio = Double.parseDouble(precio6);
        Double subTotal = (precio * cantidad6) - (((precio * cantidad6)/100) * descuento);

        if (!btnComida6.getText().equals("Vacio")) {
            int estado = ventanaPrincipal.getVentanaActual();
            if (estado == 1) {
                ventanaProductos.setTxtDescripcion(des6);
                ventanaProductos.setTxtPrecio(precio6);
            } else {
                if (estado == 3) {
                    
                    accionesComidas.meterProducto(codigo, des6, precio, descuento, cantidad6);
                }
            }
        } else {
            ventanaProductos.getBtnCrear().setEnabled(true);
            ventanaPrincipal.mostrarPanelProductos();
        }
    }//GEN-LAST:event_btnComida6ActionPerformed

    private void btnComida7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComida7ActionPerformed
        
        Integer cant = ventanaPrincipal.cant;
        if (cantidad7 != 0) {
            if (cant == 0) {                                                    
                cantidad7 = cantidad7 + 1;
            } else {
                cantidad7 = cantidad7 + cant;
                ventanaPrincipal.cant = 0;
            }
        } else {
            if (cant == 0) {                                                    
                cantidad7 = 1;
            } else {
                cantidad7 = cant;
                ventanaPrincipal.cant = 0;
            }
        }
        Integer codigo = 0001;
        Integer descuento = 10;
        Double precio = Double.parseDouble(precio7);
        Double subTotal = (precio * cantidad7) - (((precio * cantidad7)/100) * descuento);

        if (!btnComida7.getText().equals("Vacio")) {
            int estado = ventanaPrincipal.getVentanaActual();
            if (estado == 1) {
                ventanaProductos.setTxtDescripcion(des7);
                ventanaProductos.setTxtPrecio(precio7);
            } else {
                if (estado == 3) {
                    
                    accionesComidas.meterProducto(codigo, des7, precio, descuento, cantidad7);
                }
            }
        } else {
            ventanaProductos.getBtnCrear().setEnabled(true);
            ventanaPrincipal.mostrarPanelProductos();
        }
    }//GEN-LAST:event_btnComida7ActionPerformed

    private void btnComida8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComida8ActionPerformed
        
        Integer cant = ventanaPrincipal.cant;
        if (cantidad8 != 0) {
            if (cant == 0) {                                                    
                cantidad8 = cantidad8 + 1;
            } else {
                cantidad8 = cantidad8 + cant;
                ventanaPrincipal.cant = 0;
            }
        } else {
            if (cant == 0) {                                                    
                cantidad8 = 1;
            } else {
                cantidad8 = cant;
                ventanaPrincipal.cant = 0;
            }
        }
        Integer codigo = 0001;
        Integer descuento = 10;
        Double precio = Double.parseDouble(precio8);
        Double subTotal = (precio * cantidad8) - (((precio * cantidad8)/100) * descuento);

        if (!btnComida8.getText().equals("Vacio")) {
            int estado = ventanaPrincipal.getVentanaActual();
            if (estado == 1) {
                ventanaProductos.setTxtDescripcion(des8);
                ventanaProductos.setTxtPrecio(precio8);
            } else {
                if (estado == 3) {
                    
                    accionesComidas.meterProducto(codigo, des8, precio, descuento, cantidad8);
                }
            }
        } else {
            ventanaProductos.getBtnCrear().setEnabled(true);
            ventanaPrincipal.mostrarPanelProductos();
        }
    }//GEN-LAST:event_btnComida8ActionPerformed

    private void btnComida9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComida9ActionPerformed
        
        Integer cant = ventanaPrincipal.cant;
        if (cantidad9 != 0) {
            if (cant == 0) {                                                    
                cantidad9 = cantidad9 + 1;
            } else {
                cantidad9 = cantidad9 + cant;
                ventanaPrincipal.cant = 0;
            }
        } else {
            if (cant == 0) {                                                    
                cantidad9 = 1;
            } else {
                cantidad9 = cant;
                ventanaPrincipal.cant = 0;
            }
        }
        Integer codigo = 0001;
        Integer descuento = 10;
        Double precio = Double.parseDouble(precio9);
        Double subTotal = (precio * cantidad9) - (((precio * cantidad9)/100) * descuento);

        if (!btnComida9.getText().equals("Vacio")) {
            int estado = ventanaPrincipal.getVentanaActual();
            if (estado == 1) {
                ventanaProductos.setTxtDescripcion(des9);
                ventanaProductos.setTxtPrecio(precio9);
            } else {
                if (estado == 3) {
                    
                    accionesComidas.meterProducto(codigo, des9, precio, descuento, cantidad9);
                }
            }
        } else {
            ventanaProductos.getBtnCrear().setEnabled(true);
            ventanaPrincipal.mostrarPanelProductos();
        }
    }//GEN-LAST:event_btnComida9ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnComida1;
    private javax.swing.JButton btnComida2;
    private javax.swing.JButton btnComida3;
    private javax.swing.JButton btnComida4;
    private javax.swing.JButton btnComida5;
    private javax.swing.JButton btnComida6;
    private javax.swing.JButton btnComida7;
    private javax.swing.JButton btnComida8;
    private javax.swing.JButton btnComida9;
    private javax.swing.JPanel panelComidas1;
    private javax.swing.JPanel panelComidas2;
    private javax.swing.JPanel panelComidas3;
    private javax.swing.JPanel panelComidas4;
    private javax.swing.JPanel panelComidas5;
    private javax.swing.JPanel panelComidas6;
    private javax.swing.JPanel panelComidas7;
    private javax.swing.JPanel panelComidas8;
    private javax.swing.JPanel panelComidas9;
    private javax.swing.JPanel panelSubProductos;
    // End of variables declaration//GEN-END:variables
}
