
package Principal.ventanasSubProductos;

/**
 *
 * @author NatxosS
 */
import Principal.VentanaPrincipal;
import Vista.*;
import Acciones.pedido.AccionesPedidoPostres;

public class SubPostre extends javax.swing.JPanel {

    /**
     * Creates new form SubPostre
     */
    public int botonSeleccionado = 0;
    
    public String des1 = "cOMIDA";
    public String precio1 = "4";
    
    public String des2 = "ColPOSTREa";
    public String precio2 = "9";
    
    public String des3 = "FcOMIDA";
    public String precio3 = "5";
    
    public String des4 = "FantaPOSTREL";
    public String precio4 = "54";
    
    public String des5 = "cOMIDA";
    public String precio5 = "6";
    
    public String des6 = "cervez";
    public String precio6 = "7";
    
    public String des7 = "tintPOSTREoo";
    public String precio7 = "0.25";
    
    public String des8 = "acucOMIDA1";
    public String precio8 = "74.2";
    
    public String des9 = "";
    public String precio9 = "";
    
    public VentanaPrincipal ventanaPrincipal;
    public VentanaProductos ventanaProductos;
    public AccionesPedidoPostres accionesPostres;
    
    static Integer cantidad1 = 0;
    static Integer cantidad2 = 0;
    static Integer cantidad3 = 0;
    static Integer cantidad4 = 0;
    static Integer cantidad5 = 0;
    static Integer cantidad6 = 0;
    static Integer cantidad7 = 0;
    static Integer cantidad8 = 0;
    static Integer cantidad9 = 0;
    
    public SubPostre() {
        
        initComponents();
    }
    
    public SubPostre(VentanaPrincipal ventanaPrin, VentanaProductos ventanaProd) {
        
        this.setVentanaPrincipal(ventanaPrin);
        this.ventanaProductos = ventanaProd;
        this.accionesPostres = new AccionesPedidoPostres(this);
        initComponents();
    }
    
    public VentanaPrincipal getVentanaPrincipal() {
        
        return ventanaPrincipal;
    }
    
    public void setVentanaPrincipal(VentanaPrincipal ventanaPrincipal) {
        
        this.ventanaPrincipal = ventanaPrincipal;
    }

     //////////////////////////////////////// METODOS ///////////////////////////////////
    
    public void limpiarCantidades() {
        
        cantidad1 = 0;
        cantidad2 = 0;
        cantidad3 = 0;
        cantidad4 = 0;
        cantidad5 = 0;
        cantidad6 = 0;
        cantidad7 = 0;
        cantidad8 = 0;
        cantidad9 = 0;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelSubProductos = new javax.swing.JPanel();
        panelPostre1 = new javax.swing.JPanel();
        btnPostre1 = new javax.swing.JButton();
        panelPostre2 = new javax.swing.JPanel();
        btnPostre2 = new javax.swing.JButton();
        panelPostre3 = new javax.swing.JPanel();
        btnPostre3 = new javax.swing.JButton();
        panelPostre4 = new javax.swing.JPanel();
        btnPostre4 = new javax.swing.JButton();
        panelPostre5 = new javax.swing.JPanel();
        btnPostre5 = new javax.swing.JButton();
        panelPostre6 = new javax.swing.JPanel();
        btnPostre6 = new javax.swing.JButton();
        panelPostre7 = new javax.swing.JPanel();
        btnPostre7 = new javax.swing.JButton();
        panelPostre8 = new javax.swing.JPanel();
        btnPostre8 = new javax.swing.JButton();
        panelPostre9 = new javax.swing.JPanel();
        btnPostre9 = new javax.swing.JButton();

        panelSubProductos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 255), 2));
        panelSubProductos.setLayout(new java.awt.GridLayout(3, 5, 2, 2));

        panelPostre1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
        panelPostre1.setLayout(new java.awt.BorderLayout());

        btnPostre1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnPostre1.setForeground(new java.awt.Color(255, 0, 0));
        btnPostre1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/subProductos/icon_profiteroles.jpg"))); // NOI18N
        btnPostre1.setText("Profiteroles con nata");
        btnPostre1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPostre1ActionPerformed(evt);
            }
        });
        panelPostre1.add(btnPostre1, java.awt.BorderLayout.CENTER);

        panelSubProductos.add(panelPostre1);

        panelPostre2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
        panelPostre2.setLayout(new java.awt.BorderLayout());

        btnPostre2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnPostre2.setForeground(new java.awt.Color(255, 0, 0));
        btnPostre2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/subProductos/icon_tartaqueso.jpg"))); // NOI18N
        btnPostre2.setText("Tarta de queso");
        btnPostre2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPostre2ActionPerformed(evt);
            }
        });
        panelPostre2.add(btnPostre2, java.awt.BorderLayout.CENTER);

        panelSubProductos.add(panelPostre2);

        panelPostre3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
        panelPostre3.setLayout(new java.awt.BorderLayout());

        btnPostre3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnPostre3.setForeground(new java.awt.Color(255, 0, 0));
        btnPostre3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/subProductos/icon_flan.jpg"))); // NOI18N
        btnPostre3.setText("Flan de huevo");
        btnPostre3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPostre3ActionPerformed(evt);
            }
        });
        panelPostre3.add(btnPostre3, java.awt.BorderLayout.CENTER);

        panelSubProductos.add(panelPostre3);

        panelPostre4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
        panelPostre4.setLayout(new java.awt.BorderLayout());

        btnPostre4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnPostre4.setForeground(new java.awt.Color(255, 0, 0));
        btnPostre4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/subProductos/icon_sacher.jpg"))); // NOI18N
        btnPostre4.setText("Tarta Sacher");
        btnPostre4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPostre4ActionPerformed(evt);
            }
        });
        panelPostre4.add(btnPostre4, java.awt.BorderLayout.CENTER);

        panelSubProductos.add(panelPostre4);

        panelPostre5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
        panelPostre5.setLayout(new java.awt.BorderLayout());

        btnPostre5.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        btnPostre5.setForeground(new java.awt.Color(255, 0, 0));
        btnPostre5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/subProductos/icon_semi.jpg"))); // NOI18N
        btnPostre5.setText("Semifrio choco/naran");
        btnPostre5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPostre5ActionPerformed(evt);
            }
        });
        panelPostre5.add(btnPostre5, java.awt.BorderLayout.CENTER);

        panelSubProductos.add(panelPostre5);

        panelPostre6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
        panelPostre6.setLayout(new java.awt.BorderLayout());

        btnPostre6.setText("Vacio");
        btnPostre6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPostre6ActionPerformed(evt);
            }
        });
        panelPostre6.add(btnPostre6, java.awt.BorderLayout.CENTER);

        panelSubProductos.add(panelPostre6);

        panelPostre7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
        panelPostre7.setLayout(new java.awt.BorderLayout());

        btnPostre7.setText("Vacio");
        btnPostre7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPostre7ActionPerformed(evt);
            }
        });
        panelPostre7.add(btnPostre7, java.awt.BorderLayout.CENTER);

        panelSubProductos.add(panelPostre7);

        panelPostre8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
        panelPostre8.setLayout(new java.awt.BorderLayout());

        btnPostre8.setText("Vacio");
        btnPostre8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPostre8ActionPerformed(evt);
            }
        });
        panelPostre8.add(btnPostre8, java.awt.BorderLayout.CENTER);

        panelSubProductos.add(panelPostre8);

        panelPostre9.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 153, 0), 2, true));
        panelPostre9.setLayout(new java.awt.BorderLayout());

        btnPostre9.setText("Vacio");
        btnPostre9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPostre9ActionPerformed(evt);
            }
        });
        panelPostre9.add(btnPostre9, java.awt.BorderLayout.CENTER);

        panelSubProductos.add(panelPostre9);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(panelSubProductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(panelSubProductos, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnPostre1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPostre1ActionPerformed
        
        Integer cant = ventanaPrincipal.cant;
        if (cantidad1 != 0) {
            if (cant == 0) {                                                    
                cantidad1 = cantidad1 + 1;
            } else {
                cantidad1 = cantidad1 + cant;
                ventanaPrincipal.cant = 0;
            }
        } else {
            if (cant == 0) {                                                    
                cantidad1 = 1;
            } else {
                cantidad1 = cant;
                ventanaPrincipal.cant = 0;
            }
        }
        Integer codigo = 0001;
        Integer descuento = 10;
        Double precio = Double.parseDouble(precio1);
        Double subTotal = (precio * cantidad1) - (((precio * cantidad1)/100) * descuento);

        if (!btnPostre1.getText().equals("Vacio")) {
            int estado = ventanaPrincipal.getVentanaActual();
            if (estado == 1) {
                ventanaProductos.setTxtDescripcion(des1);
                ventanaProductos.setTxtPrecio(precio1);
            } else {
                if (estado == 3) {
                    
                    accionesPostres.meterProducto(codigo, des1, precio, descuento, cantidad1);
                }
            }
        } else {
            ventanaProductos.getBtnCrear().setEnabled(true);
            ventanaPrincipal.mostrarPanelProductos();
        }
    }//GEN-LAST:event_btnPostre1ActionPerformed

    private void btnPostre2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPostre2ActionPerformed
        
        Integer cant = ventanaPrincipal.cant;
        if (cantidad2 != 0) {
            if (cant == 0) {                                                    
                cantidad2 = cantidad2 + 1;
            } else {
                cantidad2 = cantidad2 + cant;
                ventanaPrincipal.cant = 0;
            }
        } else {
            if (cant == 0) {                                                    
                cantidad2 = 1;
            } else {
                cantidad2 = cant;
                ventanaPrincipal.cant = 0;
            }
        }
        Integer codigo = 0001;
        Integer descuento = 10;
        Double precio = Double.parseDouble(precio2);
        Double subTotal = (precio * cantidad2) - (((precio * cantidad2)/100) * descuento);

        if (!btnPostre2.getText().equals("Vacio")) {
            int estado = ventanaPrincipal.getVentanaActual();
            if (estado == 1) {
                ventanaProductos.setTxtDescripcion(des2);
                ventanaProductos.setTxtPrecio(precio2);
            } else {
                if (estado == 3) {
                    
                    accionesPostres.meterProducto(codigo, des2, precio, descuento, cantidad2);
                }
            }
        } else {
            ventanaProductos.getBtnCrear().setEnabled(true);
            ventanaPrincipal.mostrarPanelProductos();
        }
    }//GEN-LAST:event_btnPostre2ActionPerformed

    private void btnPostre3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPostre3ActionPerformed
        
        Integer cant = ventanaPrincipal.cant;
        if (cantidad3 != 0) {
            if (cant == 0) {                                                    
                cantidad3 = cantidad3 + 1;
            } else {
                cantidad3 = cantidad3 + cant;
                ventanaPrincipal.cant = 0;
            }
        } else {
            if (cant == 0) {                                                    
                cantidad3 = 1;
            } else {
                cantidad3 = cant;
                ventanaPrincipal.cant = 0;
            }
        }
        Integer codigo = 0001;
        Integer descuento = 10;
        Double precio = Double.parseDouble(precio3);
        Double subTotal = (precio * cantidad3) - (((precio * cantidad3)/100) * descuento);

        if (!btnPostre3.getText().equals("Vacio")) {
            int estado = ventanaPrincipal.getVentanaActual();
            if (estado == 1) {
                ventanaProductos.setTxtDescripcion(des3);
                ventanaProductos.setTxtPrecio(precio3);
            } else {
                if (estado == 3) {
                    
                    accionesPostres.meterProducto(codigo, des3, precio, descuento, cantidad3);
                }
            }
        } else {
            ventanaProductos.getBtnCrear().setEnabled(true);
            ventanaPrincipal.mostrarPanelProductos();
        }
    }//GEN-LAST:event_btnPostre3ActionPerformed

    private void btnPostre4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPostre4ActionPerformed
        
        Integer cant = ventanaPrincipal.cant;
        if (cantidad4 != 0) {
            if (cant == 0) {                                                    
                cantidad4 = cantidad4 + 1;
            } else {
                cantidad4 = cantidad4 + cant;
                ventanaPrincipal.cant = 0;
            }
        } else {
            if (cant == 0) {                                                    
                cantidad4 = 1;
            } else {
                cantidad4 = cant;
                ventanaPrincipal.cant = 0;
            }
        }
        Integer codigo = 0001;
        Integer descuento = 10;
        Double precio = Double.parseDouble(precio4);
        Double subTotal = (precio * cantidad4) - (((precio * cantidad4)/100) * descuento);

        if (!btnPostre4.getText().equals("Vacio")) {
            int estado = ventanaPrincipal.getVentanaActual();
            if (estado == 1) {
                ventanaProductos.setTxtDescripcion(des4);
                ventanaProductos.setTxtPrecio(precio4);
            } else {
                if (estado == 3) {
                    
                    accionesPostres.meterProducto(codigo, des4, precio, descuento, cantidad4);
                }
            }
        } else {
            ventanaProductos.getBtnCrear().setEnabled(true);
            ventanaPrincipal.mostrarPanelProductos();
        }
    }//GEN-LAST:event_btnPostre4ActionPerformed

    private void btnPostre5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPostre5ActionPerformed
        
        Integer cant = ventanaPrincipal.cant;
        if (cantidad5 != 0) {
            if (cant == 0) {                                                    
                cantidad5 = cantidad5 + 1;
            } else {
                cantidad5 = cantidad5 + cant;
                ventanaPrincipal.cant = 0;
            }
        } else {
            if (cant == 0) {                                                    
                cantidad5 = 1;
            } else {
                cantidad5 = cant;
                ventanaPrincipal.cant = 0;
            }
        }
        Integer codigo = 0001;
        Integer descuento = 10;
        Double precio = Double.parseDouble(precio5);
        Double subTotal = (precio * cantidad5) - (((precio * cantidad5)/100) * descuento);

        if (!btnPostre5.getText().equals("Vacio")) {
            int estado = ventanaPrincipal.getVentanaActual();
            if (estado == 1) {
                ventanaProductos.setTxtDescripcion(des5);
                ventanaProductos.setTxtPrecio(precio5);
            } else {
                if (estado == 3) {
                    
                    accionesPostres.meterProducto(codigo, des5, precio, descuento, cantidad5);
                }
            }
        } else {
            ventanaProductos.getBtnCrear().setEnabled(true);
            ventanaPrincipal.mostrarPanelProductos();
        }
    }//GEN-LAST:event_btnPostre5ActionPerformed

    private void btnPostre6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPostre6ActionPerformed
        
        Integer cant = ventanaPrincipal.cant;
        if (cantidad6 != 0) {
            if (cant == 0) {                                                    
                cantidad6 = cantidad6 + 1;
            } else {
                cantidad6 = cantidad6 + cant;
                ventanaPrincipal.cant = 0;
            }
        } else {
            if (cant == 0) {                                                    
                cantidad6 = 1;
            } else {
                cantidad6 = cant;
                ventanaPrincipal.cant = 0;
            }
        }
        Integer codigo = 0001;
        Integer descuento = 10;
        Double precio = Double.parseDouble(precio6);
        Double subTotal = (precio * cantidad6) - (((precio * cantidad6)/100) * descuento);

        if (!btnPostre6.getText().equals("Vacio")) {
            int estado = ventanaPrincipal.getVentanaActual();
            if (estado == 1) {
                ventanaProductos.setTxtDescripcion(des6);
                ventanaProductos.setTxtPrecio(precio6);
            } else {
                if (estado == 3) {
                    
                    accionesPostres.meterProducto(codigo, des6, precio, descuento, cantidad6);
                }
            }
        } else {
            ventanaProductos.getBtnCrear().setEnabled(true);
            ventanaPrincipal.mostrarPanelProductos();
        }
    }//GEN-LAST:event_btnPostre6ActionPerformed

    private void btnPostre7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPostre7ActionPerformed
        
        Integer cant = ventanaPrincipal.cant;
        if (cantidad7 != 0) {
            if (cant == 0) {                                                    
                cantidad7 = cantidad7 + 1;
            } else {
                cantidad7 = cantidad7 + cant;
                ventanaPrincipal.cant = 0;
            }
        } else {
            if (cant == 0) {                                                    
                cantidad7 = 1;
            } else {
                cantidad7 = cant;
                ventanaPrincipal.cant = 0;
            }
        }
        Integer codigo = 0001;
        Integer descuento = 10;
        Double precio = Double.parseDouble(precio7);
        Double subTotal = (precio * cantidad7) - (((precio * cantidad7)/100) * descuento);

        if (!btnPostre7.getText().equals("Vacio")) {
            int estado = ventanaPrincipal.getVentanaActual();
            if (estado == 1) {
                ventanaProductos.setTxtDescripcion(des7);
                ventanaProductos.setTxtPrecio(precio7);
            } else {
                if (estado == 3) {
                    
                    accionesPostres.meterProducto(codigo, des7, precio, descuento, cantidad7);
                }
            }
        } else {
            ventanaProductos.getBtnCrear().setEnabled(true);
            ventanaPrincipal.mostrarPanelProductos();
        }
    }//GEN-LAST:event_btnPostre7ActionPerformed

    private void btnPostre8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPostre8ActionPerformed
       
        Integer cant = ventanaPrincipal.cant;
        if (cantidad8 != 0) {
            if (cant == 0) {                                                    
                cantidad8 = cantidad8 + 1;
            } else {
                cantidad8 = cantidad8 + cant;
                ventanaPrincipal.cant = 0;
            }
        } else {
            if (cant == 0) {                                                    
                cantidad8 = 1;
            } else {
                cantidad8 = cant;
                ventanaPrincipal.cant = 0;
            }
        }
        Integer codigo = 0001;
        Integer descuento = 10;
        Double precio = Double.parseDouble(precio8);
        Double subTotal = (precio * cantidad8) - (((precio * cantidad8)/100) * descuento);

        if (!btnPostre8.getText().equals("Vacio")) {
            int estado = ventanaPrincipal.getVentanaActual();
            if (estado == 1) {
                ventanaProductos.setTxtDescripcion(des8);
                ventanaProductos.setTxtPrecio(precio8);
            } else {
                if (estado == 3) {
                    
                    accionesPostres.meterProducto(codigo, des8, precio, descuento, cantidad8);
                }
            }
        } else {
            ventanaProductos.getBtnCrear().setEnabled(true);
            ventanaPrincipal.mostrarPanelProductos();
        }
    }//GEN-LAST:event_btnPostre8ActionPerformed

    private void btnPostre9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPostre9ActionPerformed
        
        Integer cant = ventanaPrincipal.cant;
        if (cantidad9 != 0) {
            if (cant == 0) {                                                    
                cantidad9 = cantidad9 + 1;
            } else {
                cantidad9 = cantidad9 + cant;
                ventanaPrincipal.cant = 0;
            }
        } else {
            if (cant == 0) {                                                    
                cantidad9 = 1;
            } else {
                cantidad9 = cant;
                ventanaPrincipal.cant = 0;
            }
        }
        Integer codigo = 0001;
        Integer descuento = 10;
        Double precio = Double.parseDouble(precio9);
        Double subTotal = (precio * cantidad9) - (((precio * cantidad9)/100) * descuento);

        if (!btnPostre9.getText().equals("Vacio")) {
            int estado = ventanaPrincipal.getVentanaActual();
            if (estado == 1) {
                ventanaProductos.setTxtDescripcion(des9);
                ventanaProductos.setTxtPrecio(precio9);
            } else {
                if (estado == 3) {
                    
                    accionesPostres.meterProducto(codigo, des9, precio, descuento, cantidad9);
                }
            }
        } else {
            ventanaProductos.getBtnCrear().setEnabled(true);
            ventanaPrincipal.mostrarPanelProductos();
        }
    }//GEN-LAST:event_btnPostre9ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPostre1;
    private javax.swing.JButton btnPostre2;
    private javax.swing.JButton btnPostre3;
    private javax.swing.JButton btnPostre4;
    private javax.swing.JButton btnPostre5;
    private javax.swing.JButton btnPostre6;
    private javax.swing.JButton btnPostre7;
    private javax.swing.JButton btnPostre8;
    private javax.swing.JButton btnPostre9;
    private javax.swing.JPanel panelPostre1;
    private javax.swing.JPanel panelPostre2;
    private javax.swing.JPanel panelPostre3;
    private javax.swing.JPanel panelPostre4;
    private javax.swing.JPanel panelPostre5;
    private javax.swing.JPanel panelPostre6;
    private javax.swing.JPanel panelPostre7;
    private javax.swing.JPanel panelPostre8;
    private javax.swing.JPanel panelPostre9;
    private javax.swing.JPanel panelSubProductos;
    // End of variables declaration//GEN-END:variables
}
